In [1]:
from keras.models import load_model
import numpy as np
from keras.preprocessing import image
from keras.preprocessing.image import load_img

model = load_model('model/model.hdf5')

C:\Users\coda\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
img = load_img('data/1',target_size=(150,150))
img = image.img_to_array(img) / 255.0
img = np.expand_dims(img, axis=0)
predictions = model.predict(img)
print (predictions)

[[1. 0. 0. 0.]]


In [11]:
img = load_img('data/4',target_size=(150,150))
img = image.img_to_array(img) / 255.0
img = np.expand_dims(img, axis=0)
predictions = model.predict(img)
print (predictions)

[[0. 0. 0. 1.]]


In [13]:
img = load_img('data/3',target_size=(150,150))
img = image.img_to_array(img) / 255.0
img = np.expand_dims(img, axis=0)
predictions = model.predict(img)
print (predictions)

[[0. 0. 1. 0.]]


In [18]:
img = load_img('data/2',target_size=(150,150))
img = image.img_to_array(img) / 255.0
img = np.expand_dims(img, axis=0)
predictions = model.predict(img)
print (predictions)

[[0.04539079 0.7985343  0.13869229 0.01738265]]
